### ISSUE TITLE
木のマーカーを使わない方法

### ISSUE THREAD

**Issue by chibi314** [tongtybj/jsk_uav_forest#124]
@tongtybj 

競技では赤いマーカーのついた木を目印にしてタスクを行いましたが，競技会の後の（本当の）森林では赤いマーカーがないので，適当な木を最初の木としてタスクをやったと思うんですがその時使った方法は分かるでしょうか？

**Comment by tongtybj** [comment]
うろ覚えだけど、半径ｘメートル以内の木のうち、機体のｘ軸との角度が最小のものを最初の木としてた気がする

**Comment by chibi314** [comment]
具体的にどのへんをいじったか分かるでしょうか？
jsk_uav_forest_perception/src/tree_tracking.cppを書き換えるしかないでしょうか

**Comment by chibi314** [comment]
よく見たら別ブランチでコミットがありました
https://github.com/tongtybj/jsk_uav_forest/commit/9dbb093926610897cb62fcab31d68816be689da9
