### ISSUE TITLE
Remote visualization

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/jsk_uav_forest#33]
@KahnShi @chibi314 

Right now we only send the scan data and compressed image data to remote PC.
What else we need to know when observing from PC?
For example, we need the target tree position.

Besides, we need to display the necessary data in rviz as much as possible. like [here](https://cloud.githubusercontent.com/assets/3666095/15987858/d157d600-3074-11e6-95ec-71b65990b693.png)

**Comment by tongtybj** [comment]
#55 is a good example

**Comment by chibi314** [comment]
Tree target and radius(rviz message) is also necessary as well as state machine.
The frequency should be 1~2Hz.

**Comment by tongtybj** [comment]
Also the time

**Comment by chibi314** [comment]
@tongtybj 
[anzai/visualization](https://github.com/chibi314/jsk_uav_forest/tree/visualization)
を一旦実行して見ていただけますでしょうか。
timeの表示がダサい？

**Comment by chibi314** [comment]
Sent PR #62.
UAV-PC間の通信部分にメッセージを足すのをやっていないです

**Comment by chibi314** [comment]
#62 にて一旦完成させました。

**Comment by chibi314** [comment]
target posが必要
topicは/tree_global_location でしょうか。

**Comment by chibi314** [comment]
topicは/tree_locationだった
tree_global_locationのframeが/worldになってしまっているのは本当は直すべき

**Comment by chibi314** [comment]
#98 で /tree_locationを追加。
