### ISSUE TITLE
[Motion] the yaw control problem

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/jsk_uav_forest#41]
We confirmed the yaw wired problem, that is, a big rotation after the circle motion.

I wonder that the absolute value of [this line](https://github.com/tongtybj/jsk_uav_forest/blob/master/jsk_uav_forest_motion/script/circle_motion.py#L180)  is bigger that math.pi.

Usually, to solve this what I did is like [this](https://github.com/tongtybj/aerial_robot/blob/devel/aerial_robot_base/src/flight_control.cpp#L508-L510)

**Comment by chibi314** [comment]
sent PR #44
