### ISSUE TITLE
Check the accuracy of the estimation of tree radius

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/jsk_uav_forest#50]
@chibi314 
During the experiment, we have to judge whether the diameter of the tree we estimate is close to the true value within the margin of the competition(10cm).

So, we have to measure the tree diameter first, and then check the estimation data every time.

Besides, the estimation results is alway bigger than the true value in the simulation environment, since the tilt of the laser.

One suggestion is to set a shrink rate for the estimated value, like 0.9.

**Comment by tongtybj** [comment]
or a more precise way is to project the laser scan to the level plane, like [hector_mapping](https://github.com/tu-darmstadt-ros-pkg/hector_slam/blob/catkin/hector_mapping/src/HectorMappingRos.cpp#L255)

**Comment by chibi314** [comment]
柏で計測した結果、直径約0.52mの木から円フィッティングによって直径0.52mと推定できたので、精度は十分と思われる。
