### ISSUE TITLE
Slope

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/jsk_uav_forest#65]
I measured the slop of the competition forest using their 3D model.
The colored tree is about 1.5m higher than the start point, indicating that the takeoff height can not be lower than 1.5m, maybe 2m is good.

One thing I am worried about, is the strategy of task2, which can get bonus points if do the circle motion in different height. However, 2m is the middle height, so we have to descend to reach lower layer or to ascend to reach higher layer.

**Comment by tongtybj** [comment]
the angle of slope is about 10 degree.
the distance between start point and target tree is 8m

**Comment by tongtybj** [comment]
@chibi314 

2Mでもいいんだけど、一つ心配なのは高度が高すぎると枝とか葉っぱにあたってしまうこと。
3Dモデルだと, スタート地点付近で高さ2Mで飛ばすと葉っぱに当たるけど、ビデオを見る限り、その枝自体切られているみたい。要は、takeoff高度でターゲット木がスキャンできることなんだけど、1.5Mはギリギリのラインだね。

簡単な提案としては、認識する前のtakeoff時は何も考えず, 数メートル前に進む, 例えば3M. それから認識を開始する。それだと、 1.5メートルでもscanで木を捉えられる。
要は, 最初のtakeoffの目標値は: [0,0,1.5] -> [3, 0, 1.5]にすればいいじゃないかな。

**Comment by tongtybj** [comment]
722c615b7f218975860c33e3e6bfab999876acb9 で対策した。

**Comment by chibi314** [comment]
5/17 検見川にて試験
主にmotionのパラメータを調整して、高度制御や認識に問題がないことを確認した。
