### ISSUE TITLE
Special color tree

### ISSUE THREAD

**Issue by chibi314** [tongtybj/jsk_uav_forest#83]
[これ](https://github.com/tongtybj/jsk_uav_forest/blob/master/jsk_uav_forest_perception/src/tree_database.cpp#L155)ですが、最もvoteが多い木の色が変わるようになっていると思います。

**Comment by tongtybj** [comment]
20番の立ち木のポインターを覚えておくこと。

**Comment by chibi314** [comment]
Sent PR #92
