### ISSUE TITLE
Search center is not updated

### ISSUE THREAD

**Issue by chibi314** [tongtybj/jsk_uav_forest#84]
[これ](https://github.com/tongtybj/jsk_uav_forest/blob/master/jsk_uav_forest_perception/src/tree_tracking.cpp#L104)で、search_centerが更新されないので、20番の木の周囲~mの木を対象とするという動作ではなくなっていると思います。

**Comment by tongtybj** [comment]
serch_centerによるfilter機能を廃止しようとおもいます。

**Comment by chibi314** [comment]
filter機能は廃止して大丈夫なのですが、search_center_自体は使いたいので、今のまま残すか、できれば #92 を使ってtree_tracking.cpp内でも20番のグローバル座標がわかるとよいのですが、できますでしょうか。

**Comment by chibi314** [comment]
Sent PR #94
