### ISSUE TITLE
Wrong time of result file

### ISSUE THREAD

**Issue by chibi314** [tongtybj/jsk_uav_forest#89]
@tongtybj 
14:46ごろにログ出力を実行したところ、2017-05-15-5-46-trees.yamlができました。時間が5時になっています。
[ここ](http://www.02.246.ne.jp/~torutk/cxx/boost/datetime.html)で調べて
`boost::posix_time::ptime t = boost::posix_time::second_clock::local_time();`
としたら、正しい時間になりましたが、そちらのPCではどうなりますか。

**Comment by tongtybj** [comment]
そうか, boost::posixのほうでローカルタイムにすることができるんだね。
今はUTCタイムに合わせているから、9時間遅れている。

それと、pythonスクリプト(2Dmap情報)の方でもファイルの書き出しがあって:
https://github.com/tongtybj/jsk_uav_forest/blob/master/jsk_uav_forest_perception/scripts/mapping.py#L51
こっちはわざわざUTCに合わせている。

直してくれるかな。
1.  ```boost::posix_time::ptime t = boost::posix_time::second_clock::local_time() ```を使う
2. ```  dt_obj = datetime.fromtimestamp(rospy.get_time())``` にする

**Comment by chibi314** [comment]
Sent PR #90
